server:
  port: 8080

spring:

  mail:
    host: smtp.googlemail.com
    port: 587
    username: thongbao.truyenmeme@gmail.com
    password: qijsscfvbqrcrmrb
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
parallel-check:
  rule1: true
  rule2: false
  rule3: true