server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_boot_base_crud
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

#http://localhost:8080/swagger-ui/index.html