server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_boot_base_crud
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  #http://localhost:8080/swagger-ui/index.html

  mail:
    host: smtp.googlemail.com
    port: 587
    username: thongbao.truyenmeme@gmail.com
    password: qijsscfvbqrcrmrb
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
